site_name: Plasmid
site_description: Plasmid is a library for creating server-side minigames with Fabric.
site_author: NucleoidMC
theme: readthedocs
nav:
    - Home: index.md
    - 'Full Setup Guide': 'full-setup.md'